env:
  commonjs: true
  es6: true
  node: true
extends:
  - react-app
  - react-app/jest
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:prettier/recommended
  - prettier
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
    - react-hooks
rules:
    react-hooks/exhaustive-deps: 0
